//! Request-reply correlation.
//!
//! Each outbound [`crate::inbox::BusMessage::Request`] carries a
//! [`CorrelationId`] generated by the requester. The matching
//! [`crate::inbox::BusMessage::Reply`] echoes that id back so the bus
//! can route the response to the right waiter. [`ReplyWaiter`] holds
//! the in-flight oneshot senders, keyed by correlation and bound to the
//! expected responder's authenticated agent fingerprint.

use agent_mesh_protocol::Fingerprint;
use rand::RngCore;
use std::collections::HashMap;
use std::sync::Mutex;
use tokio::sync::oneshot;

/// A 16-byte correlation identifier.
///
/// 128 bits is enough collision space that the requester can draw a
/// fresh one at random without coordination, even at very high request
/// rates. The bytes are echoed verbatim in the reply.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CorrelationId(pub [u8; 16]);

impl CorrelationId {
    /// Draw a fresh random correlation id from the OS RNG.
    #[must_use]
    pub fn new_random() -> Self {
        let mut id = [0u8; 16];
        rand::thread_rng().fill_bytes(&mut id);
        Self(id)
    }

    /// Full 32-character hex representation. For log lines and the
    /// `CorrelationId` round-trip in `BusMessage`.
    #[must_use]
    pub fn hex(&self) -> String {
        hex::encode(self.0)
    }
}

/// The result of attempting to deliver a reply to an in-flight waiter.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReplyDelivery {
    /// The expected peer's reply completed the waiter.
    Delivered,
    /// No waiter exists for the correlation id.
    Unknown,
    /// The supplied reply signer was not the request's target.
    PeerMismatch {
        /// Agent fingerprint the request was sent to.
        expected_peer_fp: Fingerprint,
        /// Verified agent fingerprint that signed the reply.
        actual_peer_fp: Fingerprint,
    },
    /// The request receiver was dropped without explicitly cancelling its waiter.
    ReceiverDropped,
}

struct PendingReply {
    expected_peer_fp: Fingerprint,
    sender: oneshot::Sender<Vec<u8>>,
}

/// Non-consuming responder check used before an inbound reply mutates replay
/// state. Delivery repeats this comparison while removing the waiter, so a
/// concurrent cancellation or replacement cannot bypass the binding.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ReplyPeerCheck {
    Expected,
    Unknown,
    PeerMismatch {
        expected_peer_fp: Fingerprint,
        actual_peer_fp: Fingerprint,
    },
}

/// Holds oneshot senders for in-flight requests, keyed by correlation and
/// bound to the expected responder fingerprint.
///
/// `register` returns the receiver half of a oneshot; the bus's inbox
/// later calls `deliver` when the matching reply arrives. If the
/// request times out or the bus shuts down before the reply, the
/// waiter is dropped (or explicitly cancelled) and any late reply is
/// silently discarded.
#[derive(Default)]
pub struct ReplyWaiter {
    waiters: Mutex<HashMap<CorrelationId, PendingReply>>,
}

impl ReplyWaiter {
    /// Build a fresh waiter with no in-flight requests.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a fresh correlation id, atomically binding it to
    /// `expected_peer_fp`, and return the receiver the caller will await.
    pub fn register(
        &self,
        id: CorrelationId,
        expected_peer_fp: Fingerprint,
    ) -> oneshot::Receiver<Vec<u8>> {
        let (tx, rx) = oneshot::channel();
        self.waiters.lock().expect("reply waiter poisoned").insert(
            id,
            PendingReply {
                expected_peer_fp,
                sender: tx,
            },
        );
        rx
    }

    /// Deliver a reply payload signed by `actual_peer_fp` to the waiter for
    /// `id`.
    ///
    /// The fingerprint comparison and matching removal happen while holding
    /// the same lock. A reply from any other verified signer returns
    /// [`ReplyDelivery::PeerMismatch`] without consuming the waiter, leaving
    /// the expected peer free to complete it later.
    pub fn deliver(
        &self,
        id: CorrelationId,
        actual_peer_fp: Fingerprint,
        payload: Vec<u8>,
    ) -> ReplyDelivery {
        let pending = {
            let mut waiters = self.waiters.lock().expect("reply waiter poisoned");
            let Some(pending) = waiters.get(&id) else {
                return ReplyDelivery::Unknown;
            };
            if pending.expected_peer_fp != actual_peer_fp {
                return ReplyDelivery::PeerMismatch {
                    expected_peer_fp: pending.expected_peer_fp,
                    actual_peer_fp,
                };
            }
            waiters
                .remove(&id)
                .expect("reply waiter disappeared while lock was held")
        };

        if pending.sender.send(payload).is_ok() {
            ReplyDelivery::Delivered
        } else {
            ReplyDelivery::ReceiverDropped
        }
    }

    /// Check whether `actual_peer_fp` is the expected signer for `id` without
    /// consuming or otherwise changing the waiter.
    pub(crate) fn check_peer(
        &self,
        id: CorrelationId,
        actual_peer_fp: Fingerprint,
    ) -> ReplyPeerCheck {
        let waiters = self.waiters.lock().expect("reply waiter poisoned");
        match waiters.get(&id) {
            None => ReplyPeerCheck::Unknown,
            Some(pending) if pending.expected_peer_fp == actual_peer_fp => ReplyPeerCheck::Expected,
            Some(pending) => ReplyPeerCheck::PeerMismatch {
                expected_peer_fp: pending.expected_peer_fp,
                actual_peer_fp,
            },
        }
    }

    /// Drop the waiter for `id` without delivering anything.
    ///
    /// Called by the bus when a request times out — keeps the waiters
    /// map from accumulating dead entries.
    pub fn cancel(&self, id: &CorrelationId) {
        self.waiters
            .lock()
            .expect("reply waiter poisoned")
            .remove(id);
    }

    /// Number of in-flight waiters. For tests + diagnostics.
    #[must_use]
    pub fn pending(&self) -> usize {
        self.waiters.lock().expect("reply waiter poisoned").len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn peer(seed: u8) -> Fingerprint {
        Fingerprint([seed; 32])
    }

    #[test]
    fn correlation_ids_are_distinct() {
        let a = CorrelationId::new_random();
        let b = CorrelationId::new_random();
        assert_ne!(a, b, "two random ids must not collide");
        assert_eq!(a.hex().len(), 32);
    }

    #[test]
    fn correlation_id_hex_is_deterministic() {
        let id = CorrelationId([0xab; 16]);
        assert_eq!(id.hex(), "abababababababababababababababab");
    }

    #[tokio::test]
    async fn register_returns_receiver_completed_on_deliver() {
        let w = ReplyWaiter::new();
        let id = CorrelationId::new_random();
        let expected = peer(1);
        let rx = w.register(id, expected);
        assert_eq!(w.pending(), 1);
        assert_eq!(
            w.deliver(id, expected, b"reply".to_vec()),
            ReplyDelivery::Delivered
        );
        assert_eq!(rx.await.unwrap(), b"reply");
        assert_eq!(w.pending(), 0, "deliver removes the waiter");
    }

    #[test]
    fn deliver_unknown_id_is_reported() {
        let w = ReplyWaiter::new();
        assert_eq!(
            w.deliver(CorrelationId::new_random(), peer(1), b"orphan".to_vec()),
            ReplyDelivery::Unknown
        );
    }

    #[tokio::test]
    async fn mismatched_peer_does_not_consume_waiter() {
        let w = ReplyWaiter::new();
        let id = CorrelationId::new_random();
        let expected = peer(1);
        let attacker = peer(2);
        let rx = w.register(id, expected);

        assert_eq!(
            w.deliver(id, attacker, b"forged".to_vec()),
            ReplyDelivery::PeerMismatch {
                expected_peer_fp: expected,
                actual_peer_fp: attacker,
            }
        );
        assert_eq!(w.pending(), 1, "mismatch must leave the waiter pending");

        assert_eq!(
            w.deliver(id, expected, b"legitimate".to_vec()),
            ReplyDelivery::Delivered
        );
        assert_eq!(rx.await.unwrap(), b"legitimate");
        assert_eq!(w.pending(), 0);
    }

    #[tokio::test]
    async fn cancel_removes_waiter() {
        let w = ReplyWaiter::new();
        let id = CorrelationId::new_random();
        let expected = peer(1);
        let rx = w.register(id, expected);
        assert_eq!(w.pending(), 1);
        w.cancel(&id);
        assert_eq!(w.pending(), 0);
        // Receiver gets closed → recv resolves to Err.
        assert!(rx.await.is_err());
        // Late delivery is silently dropped.
        assert_eq!(
            w.deliver(id, expected, b"late".to_vec()),
            ReplyDelivery::Unknown
        );
    }

    #[tokio::test]
    async fn deliver_twice_only_first_wins() {
        let w = ReplyWaiter::new();
        let id = CorrelationId::new_random();
        let expected = peer(1);
        let rx = w.register(id, expected);
        assert_eq!(
            w.deliver(id, expected, b"first".to_vec()),
            ReplyDelivery::Delivered
        );
        // Second delivery → no waiter left, reports Unknown.
        assert_eq!(
            w.deliver(id, expected, b"second".to_vec()),
            ReplyDelivery::Unknown
        );
        assert_eq!(rx.await.unwrap(), b"first");
    }

    #[test]
    fn dropped_receiver_is_reported_and_waiter_is_removed() {
        let w = ReplyWaiter::new();
        let id = CorrelationId::new_random();
        let expected = peer(1);
        drop(w.register(id, expected));

        assert_eq!(
            w.deliver(id, expected, b"unobserved".to_vec()),
            ReplyDelivery::ReceiverDropped
        );
        assert_eq!(w.pending(), 0);
    }
}
